# Generated by Django 4.1.6 on 2023-02-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuruApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hamburguer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=250)),
                ('productLine', models.CharField(max_length=250)),
                ('productDescription', models.TextField(max_length=500)),
                ('productPrice', models.FloatField()),
            ],
        ),
    ]
